// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnJXb2UKm0G-OAUpiEhgskIKFFEvvM8_s',
    appId: '1:673765563517:web:8a4af278ba1762fb2f6514',
    messagingSenderId: '673765563517',
    projectId: 'employee-db-fbf87',
    authDomain: 'employee-db-fbf87.firebaseapp.com',
    databaseURL: 'https://employee-db-fbf87-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-fbf87.firebasestorage.app',
    measurementId: 'G-FV809HS5EM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvGBGTsvPzAdLkUpNZWm2ndQu-tHdmIC8',
    appId: '1:673765563517:android:4070ba65c7f012502f6514',
    messagingSenderId: '673765563517',
    projectId: 'employee-db-fbf87',
    databaseURL: 'https://employee-db-fbf87-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-fbf87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwcVVJOzT4vzCEUnf84Y43HvGGOmwj3vE',
    appId: '1:673765563517:ios:3a34d0f4552f74332f6514',
    messagingSenderId: '673765563517',
    projectId: 'employee-db-fbf87',
    databaseURL: 'https://employee-db-fbf87-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-fbf87.firebasestorage.app',
    iosBundleId: 'com.example.employeeAlya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwcVVJOzT4vzCEUnf84Y43HvGGOmwj3vE',
    appId: '1:673765563517:ios:3a34d0f4552f74332f6514',
    messagingSenderId: '673765563517',
    projectId: 'employee-db-fbf87',
    databaseURL: 'https://employee-db-fbf87-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-fbf87.firebasestorage.app',
    iosBundleId: 'com.example.employeeAlya',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnJXb2UKm0G-OAUpiEhgskIKFFEvvM8_s',
    appId: '1:673765563517:web:43c6d268284faf412f6514',
    messagingSenderId: '673765563517',
    projectId: 'employee-db-fbf87',
    authDomain: 'employee-db-fbf87.firebaseapp.com',
    databaseURL: 'https://employee-db-fbf87-default-rtdb.firebaseio.com',
    storageBucket: 'employee-db-fbf87.firebasestorage.app',
    measurementId: 'G-9XB8N43QN1',
  );
}
